NAME1 = "Legal business name"
NAME2 = "Fictitious business name"
ADDR1 = "Address (from protocol)"
ADDR2 = "City/state/zip (from protocol)"
PHONE = "Phone number"
CATEGORY = "Type of business"
PDF = "PDF link"
REPLACEMENT = "Replacement protocol"
DATE = "Date of protocol submission"

